apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
spec:
  type: ClusterIP
  selector:
    app: my-nginx  # select all pods that has my-nginx selector
  ports:
  - port: 8080
    targetPort: 80

